/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.telefonica.services.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.telefonica.services.model.Department;
import com.telefonica.services.model.DepartmentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Department service. Represents a row in the &quot;staffMgmt_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.telefonica.services.model.DepartmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentImpl}.
 * </p>
 *
 * @author plazaro
 * @see DepartmentImpl
 * @see com.telefonica.services.model.Department
 * @see com.telefonica.services.model.DepartmentModel
 * @generated
 */
public class DepartmentModelImpl extends BaseModelImpl<Department>
	implements DepartmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a department model instance should use the {@link com.telefonica.services.model.Department} interface instead.
	 */
	public static final String TABLE_NAME = "staffMgmt_Department";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dpt_name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table staffMgmt_Department (dpt_name VARCHAR(75) not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table staffMgmt_Department";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.telefonica.services.model.Department"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.telefonica.services.model.Department"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.telefonica.services.model.Department"));

	public DepartmentModelImpl() {
	}

	public String getPrimaryKey() {
		return _dpt_name;
	}

	public void setPrimaryKey(String primaryKey) {
		setDpt_name(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _dpt_name;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Department.class;
	}

	public String getModelClassName() {
		return Department.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dpt_name", getDpt_name());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String dpt_name = (String)attributes.get("dpt_name");

		if (dpt_name != null) {
			setDpt_name(dpt_name);
		}
	}

	public String getDpt_name() {
		if (_dpt_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _dpt_name;
		}
	}

	public void setDpt_name(String dpt_name) {
		_dpt_name = dpt_name;
	}

	@Override
	public Department toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Department)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DepartmentImpl departmentImpl = new DepartmentImpl();

		departmentImpl.setDpt_name(getDpt_name());

		departmentImpl.resetOriginalValues();

		return departmentImpl;
	}

	public int compareTo(Department department) {
		String primaryKey = department.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Department department = null;

		try {
			department = (Department)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = department.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Department> toCacheModel() {
		DepartmentCacheModel departmentCacheModel = new DepartmentCacheModel();

		departmentCacheModel.dpt_name = getDpt_name();

		String dpt_name = departmentCacheModel.dpt_name;

		if ((dpt_name != null) && (dpt_name.length() == 0)) {
			departmentCacheModel.dpt_name = null;
		}

		return departmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{dpt_name=");
		sb.append(getDpt_name());

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append("com.telefonica.services.model.Department");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dpt_name</column-name><column-value><![CDATA[");
		sb.append(getDpt_name());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Department.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Department.class
		};
	private String _dpt_name;
	private Department _escapedModelProxy;
}