/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.telefonica.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;staffMgmt_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.services.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.services.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author plazaro
 * @see Employee
 * @see com.telefonica.services.model.impl.EmployeeImpl
 * @see com.telefonica.services.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp_id of this employee.
	 *
	 * @return the emp_id of this employee
	 */
	public long getEmp_id();

	/**
	 * Sets the emp_id of this employee.
	 *
	 * @param emp_id the emp_id of this employee
	 */
	public void setEmp_id(long emp_id);

	/**
	 * Returns the name of this employee.
	 *
	 * @return the name of this employee
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this employee.
	 *
	 * @param name the name of this employee
	 */
	public void setName(String name);

	/**
	 * Returns the dpt_name of this employee.
	 *
	 * @return the dpt_name of this employee
	 */
	@AutoEscape
	public String getDpt_name();

	/**
	 * Sets the dpt_name of this employee.
	 *
	 * @param dpt_name the dpt_name of this employee
	 */
	public void setDpt_name(String dpt_name);

	/**
	 * Returns the phone_no of this employee.
	 *
	 * @return the phone_no of this employee
	 */
	public int getPhone_no();

	/**
	 * Sets the phone_no of this employee.
	 *
	 * @param phone_no the phone_no of this employee
	 */
	public void setPhone_no(int phone_no);

	/**
	 * Returns the photo of this employee.
	 *
	 * @return the photo of this employee
	 */
	@AutoEscape
	public String getPhoto();

	/**
	 * Sets the photo of this employee.
	 *
	 * @param photo the photo of this employee
	 */
	public void setPhoto(String photo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Employee employee);

	public int hashCode();

	public CacheModel<Employee> toCacheModel();

	public Employee toEscapedModel();

	public String toString();

	public String toXmlString();
}